/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package my.spellchecker;
import java.io.IOException;
/**
 *
 * @author earapogiorgi
 */
public class SpellCheckerUI extends javax.swing.JFrame {
    /**
     * Creates new form SpellCheckerUI
     */
    public SpellCheckerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        spellCheckDialog = new javax.swing.JDialog();
        popUpTextPanel = new javax.swing.JPanel();
        wrongWordsScrollPane = new javax.swing.JScrollPane();
        wrongWordsList = new javax.swing.JList();
        altWordButton = new javax.swing.JButton();
        saveOriginalWordButton = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        alternativeWordDialog = new javax.swing.JDialog();
        altWordPanel = new javax.swing.JPanel();
        altWordScrollPane = new javax.swing.JScrollPane();
        altWordList = new javax.swing.JList();
        cancelButton2 = new javax.swing.JButton();
        replaceAltWordButton = new javax.swing.JButton();
        exceptionInOpenFileUsingPathDialog = new javax.swing.JDialog();
        exceptionLabel = new javax.swing.JLabel();
        closeExceptionWindowButton = new javax.swing.JButton();
        textDialog = new javax.swing.JDialog();
        textPanel = new javax.swing.JPanel();
        textScrollPane = new javax.swing.JScrollPane();
        textTextArea = new javax.swing.JTextArea();
        spellCheckButton = new javax.swing.JButton();
        cancelTextPanelButton = new javax.swing.JButton();
        fileDialog = new javax.swing.JDialog();
        openFilePanel = new javax.swing.JPanel();
        pathTextField = new javax.swing.JTextField();
        pathButton = new javax.swing.JButton();
        orLabel = new javax.swing.JLabel();
        openFileButton = new javax.swing.JButton();
        encodingTypeTextField = new javax.swing.JTextField();
        cancelFileDialogButton = new javax.swing.JButton();
        chooseDialog = new javax.swing.JDialog();
        choosePanel = new javax.swing.JPanel();
        chooseInsertTextButton = new javax.swing.JButton();
        chooseOpenFileButton = new javax.swing.JButton();
        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        spellCheckDialog.setMinimumSize(new java.awt.Dimension(340, 400));

        popUpTextPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wrong Spelled Words", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        wrongWordsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        wrongWordsScrollPane.setViewportView(wrongWordsList);

        altWordButton.setText("Find Alternative");
        altWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altWordButtonActionPerformed(evt);
            }
        });

        saveOriginalWordButton.setText("Save Word");

        cancelButton1.setText("Cancel");
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popUpTextPanelLayout = new javax.swing.GroupLayout(popUpTextPanel);
        popUpTextPanel.setLayout(popUpTextPanelLayout);
        popUpTextPanelLayout.setHorizontalGroup(
            popUpTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popUpTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wrongWordsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popUpTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altWordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveOriginalWordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        popUpTextPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {altWordButton, cancelButton1, saveOriginalWordButton});

        popUpTextPanelLayout.setVerticalGroup(
            popUpTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popUpTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(popUpTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popUpTextPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(altWordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveOriginalWordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton1))
                    .addComponent(wrongWordsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout spellCheckDialogLayout = new javax.swing.GroupLayout(spellCheckDialog.getContentPane());
        spellCheckDialog.getContentPane().setLayout(spellCheckDialogLayout);
        spellCheckDialogLayout.setHorizontalGroup(
            spellCheckDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popUpTextPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        spellCheckDialogLayout.setVerticalGroup(
            spellCheckDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popUpTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        alternativeWordDialog.setMinimumSize(new java.awt.Dimension(350, 300));

        altWordPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alternative Words", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        altWordList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        altWordScrollPane.setViewportView(altWordList);

        cancelButton2.setText("Cancel");
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });

        replaceAltWordButton.setText("Replace Word");

        javax.swing.GroupLayout altWordPanelLayout = new javax.swing.GroupLayout(altWordPanel);
        altWordPanel.setLayout(altWordPanelLayout);
        altWordPanelLayout.setHorizontalGroup(
            altWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altWordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(altWordScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(altWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton2)
                    .addComponent(replaceAltWordButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        altWordPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton2, replaceAltWordButton});

        altWordPanelLayout.setVerticalGroup(
            altWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altWordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(altWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(altWordPanelLayout.createSequentialGroup()
                        .addComponent(replaceAltWordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton2))
                    .addComponent(altWordScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout alternativeWordDialogLayout = new javax.swing.GroupLayout(alternativeWordDialog.getContentPane());
        alternativeWordDialog.getContentPane().setLayout(alternativeWordDialogLayout);
        alternativeWordDialogLayout.setHorizontalGroup(
            alternativeWordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altWordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        alternativeWordDialogLayout.setVerticalGroup(
            alternativeWordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altWordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        exceptionInOpenFileUsingPathDialog.setMinimumSize(new java.awt.Dimension(400, 215));
        exceptionInOpenFileUsingPathDialog.setPreferredSize(new java.awt.Dimension(400, 300));

        exceptionLabel.setFont(new java.awt.Font("Buxton Sketch", 0, 24)); // NOI18N
        exceptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exceptionLabel.setText("Problem Accessing File");

        closeExceptionWindowButton.setText("Cancel");
        closeExceptionWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeExceptionWindowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exceptionInOpenFileUsingPathDialogLayout = new javax.swing.GroupLayout(exceptionInOpenFileUsingPathDialog.getContentPane());
        exceptionInOpenFileUsingPathDialog.getContentPane().setLayout(exceptionInOpenFileUsingPathDialogLayout);
        exceptionInOpenFileUsingPathDialogLayout.setHorizontalGroup(
            exceptionInOpenFileUsingPathDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exceptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exceptionInOpenFileUsingPathDialogLayout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(closeExceptionWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        exceptionInOpenFileUsingPathDialogLayout.setVerticalGroup(
            exceptionInOpenFileUsingPathDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exceptionInOpenFileUsingPathDialogLayout.createSequentialGroup()
                .addComponent(exceptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeExceptionWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        textDialog.setMinimumSize(new java.awt.Dimension(400, 350));

        textPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Text", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        textPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        textTextArea.setColumns(20);
        textTextArea.setRows(5);
        textTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textScrollPane.setViewportView(textTextArea);

        spellCheckButton.setText("Spell Check");
        spellCheckButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spellCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spellCheckButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(textPanelLayout.createSequentialGroup()
                        .addComponent(spellCheckButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spellCheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cancelTextPanelButton.setText("Cancel");
        cancelTextPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTextPanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textDialogLayout = new javax.swing.GroupLayout(textDialog.getContentPane());
        textDialog.getContentPane().setLayout(textDialogLayout);
        textDialogLayout.setHorizontalGroup(
            textDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
            .addGroup(textDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textDialogLayout.createSequentialGroup()
                    .addGroup(textDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(textDialogLayout.createSequentialGroup()
                            .addContainerGap(393, Short.MAX_VALUE)
                            .addComponent(cancelTextPanelButton)))
                    .addContainerGap()))
        );
        textDialogLayout.setVerticalGroup(
            textDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
            .addGroup(textDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(textDialogLayout.createSequentialGroup()
                    .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cancelTextPanelButton)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );

        fileDialog.setMinimumSize(new java.awt.Dimension(550, 300));

        openFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Open File"));
        openFilePanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pathTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pathTextField.setText("Write Path");
        pathTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pathTextFieldFocusGained(evt);
            }
        });
        pathTextField.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                pathTextFieldComponentHidden(evt);
            }
        });
        pathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextFieldActionPerformed(evt);
            }
        });

        pathButton.setText("Open");
        pathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathButtonActionPerformed(evt);
            }
        });

        orLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orLabel.setText("or");

        openFileButton.setText("Open File");
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        encodingTypeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        encodingTypeTextField.setText("Write Encoding Type");
        encodingTypeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                encodingTypeTextFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout openFilePanelLayout = new javax.swing.GroupLayout(openFilePanel);
        openFilePanel.setLayout(openFilePanelLayout);
        openFilePanelLayout.setHorizontalGroup(
            openFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(openFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(openFilePanelLayout.createSequentialGroup()
                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encodingTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        openFilePanelLayout.setVerticalGroup(
            openFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(openFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encodingTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelFileDialogButton.setText("Cancel");
        cancelFileDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFileDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileDialogLayout = new javax.swing.GroupLayout(fileDialog.getContentPane());
        fileDialog.getContentPane().setLayout(fileDialogLayout);
        fileDialogLayout.setHorizontalGroup(
            fileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
            .addGroup(fileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fileDialogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(fileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(openFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelFileDialogButton, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        fileDialogLayout.setVerticalGroup(
            fileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(fileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fileDialogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(openFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(cancelFileDialogButton)
                    .addContainerGap()))
        );

        chooseDialog.setMinimumSize(new java.awt.Dimension(250, 130));

        choosePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Spell Checking Method:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        choosePanel.setMinimumSize(new java.awt.Dimension(300, 300));

        chooseInsertTextButton.setText("Insert Text");
        chooseInsertTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseInsertTextButtonActionPerformed(evt);
            }
        });

        chooseOpenFileButton.setText("Open File");
        chooseOpenFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseOpenFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout choosePanelLayout = new javax.swing.GroupLayout(choosePanel);
        choosePanel.setLayout(choosePanelLayout);
        choosePanelLayout.setHorizontalGroup(
            choosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choosePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseInsertTextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseOpenFileButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        choosePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chooseInsertTextButton, chooseOpenFileButton});

        choosePanelLayout.setVerticalGroup(
            choosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choosePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(choosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseInsertTextButton)
                    .addComponent(chooseOpenFileButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chooseDialogLayout = new javax.swing.GroupLayout(chooseDialog.getContentPane());
        chooseDialog.getContentPane().setLayout(chooseDialogLayout);
        chooseDialogLayout.setHorizontalGroup(
            chooseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseDialogLayout.createSequentialGroup()
                .addComponent(choosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        chooseDialogLayout.setVerticalGroup(
            chooseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(choosePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomePanel.setBackground(new java.awt.Color(226, 226, 230));
        welcomePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(56, 76, 97), new java.awt.Color(56, 76, 97), new java.awt.Color(56, 76, 97), new java.awt.Color(56, 76, 97)));

        welcomeLabel.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(6, 27, 49));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome To Our Spell Checker!");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        welcomeLabel.getAccessibleContext().setAccessibleName("welcomeLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void altWordButtonActionPerformed(java.awt.event.ActionEvent evt) {
        alternativeWordDialog.setVisible(true);
    }

    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        alternativeWordDialog.setVisible(false);
    }

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        spellCheckDialog.setVisible(false);
    }

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        chooseDialog.setVisible(true);
        this.setVisible(false);
    }

    private void closeExceptionWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {
        exceptionInOpenFileUsingPathDialog.setVisible(false);
    }

    private void spellCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {
        DataInput.inputFromUser(textTextArea.getText());
        spellCheckDialog.setVisible(true);
    }

    private void cancelTextPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        textDialog.setVisible(false);
    }

    private void pathTextFieldFocusGained(java.awt.event.FocusEvent evt) {
        pathTextField.setText("");
    }

    private void pathTextFieldComponentHidden(java.awt.event.ComponentEvent evt) {
        // TODO add your handling code here:
    }

    private void pathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void pathButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        try {
            DataInput.readInputFromTxt(pathTextField.getText(), encodingTypeTextField.getText());
        } catch (IOException e) {
            exceptionInOpenFileUsingPathDialog.setVisible(true);
        }
    }

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void encodingTypeTextFieldFocusGained(java.awt.event.FocusEvent evt) {
        encodingTypeTextField.setText("");
    }

    private void cancelFileDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {
        fileDialog.setVisible(false);
    }

    private void chooseInsertTextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        textDialog.setVisible(true);
    }

    private void chooseOpenFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        fileDialog.setVisible(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpellCheckerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpellCheckerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpellCheckerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpellCheckerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpellCheckerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton altWordButton;
    private javax.swing.JList altWordList;
    private javax.swing.JPanel altWordPanel;
    private javax.swing.JScrollPane altWordScrollPane;
    private javax.swing.JDialog alternativeWordDialog;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JButton cancelFileDialogButton;
    private javax.swing.JButton cancelTextPanelButton;
    private javax.swing.JDialog chooseDialog;
    private javax.swing.JButton chooseInsertTextButton;
    private javax.swing.JButton chooseOpenFileButton;
    private javax.swing.JPanel choosePanel;
    private javax.swing.JButton closeExceptionWindowButton;
    private javax.swing.JTextField encodingTypeTextField;
    private javax.swing.JDialog exceptionInOpenFileUsingPathDialog;
    private javax.swing.JLabel exceptionLabel;
    private javax.swing.JDialog fileDialog;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JPanel openFilePanel;
    private javax.swing.JLabel orLabel;
    private javax.swing.JButton pathButton;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JPanel popUpTextPanel;
    private javax.swing.JButton replaceAltWordButton;
    private javax.swing.JButton saveOriginalWordButton;
    private javax.swing.JButton spellCheckButton;
    private javax.swing.JDialog spellCheckDialog;
    private javax.swing.JDialog textDialog;
    private javax.swing.JPanel textPanel;
    private javax.swing.JScrollPane textScrollPane;
    private javax.swing.JTextArea textTextArea;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JList wrongWordsList;
    private javax.swing.JScrollPane wrongWordsScrollPane;
    // End of variables declaration
}
